export * from './ping.controller';
export * from './categoria.controller';
export * from './personal.controller';
export * from './actividadgrupo.controller';
export * from './estudiante.controller';
export * from './jefe.controller';
export * from './departamento.controller';
export * from './listacalif.controller';
export * from './listaasist.controller';
